---
name: Build and Deploy Website to Github pages
on:
  push:
    branches: [ main ]
  jobs:
    build-and-deploy:
      name: Build and Deploy
      runs-on: ubuntu-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: yarn install

      - name: Deploy
        run: |
          git config --global user.name 'Sailesh Kasaju'
          git config --global user.email 'leosailesh@gmail.com'
          git remore set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          yarn deploy
